config/routes.rb
Rails.application.routes.draw do

  get 'systems/run'

  resources :commands

end

app/models/command.rb
class Command < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  include ActionController::Live
  before_action :set_command, only: [:show, :edit, :update, :destroy]

  def index
    @commands = Command.all
  end

  def show
    $redis.set("command", "#{@command.line}")
    @command
  end

  def new
    @command = Command.new
  end

  def edit
  end

  def create
    @command = Command.new(command_params)
    if @command.save
      redirect_to @command, notice: 'Command was successfully created.'
    else
      render :new
    end
  end

  def update
    if @command.update(command_params)
      redirect_to @command, notice: 'Command was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @command.destroy
    redirect_to commands_url, notice: 'Command was successfully destroyed.'
  end

  private
  def set_command
    @command = Command.find(params[:id])
  end

  def command_params
    params.require(:command).permit(:line)
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  include ActionController::Live
  def run
    response.headers["Content-Type"] = "text/event-stream"
    logger.info "Starting run"
    redis_cli = Redis.new
    #redis_cli.subscribe("command") do |on|
    #  logger.info redis_cli.inspect
    #  on.message do |event, data|
    #    logger.info data.inspect
    #    logger.info event.inspect
    #    response.stream.write "data: #{data}\n\n"
    #  end
    #end
    #
    command = redis_cli.multi do |multi|
      multi.get("command")
      multi.del("command")
    end
    pipe = IO.popen
    logger.info command.inspect
    ex = command.first
    if ex
      pipe(ex)
      while(line = pipe.gets)
        response.stream.write "data: #{line}\n\n"
        sleep 0.5
      end
    end
  rescue IOError
    logger.error "AN ERROR HAS OCCURED..."
  ensure
    pipe.close unless pipe.nil?
    logger.info "quitting redis"
    redis_cli.quit
    logger.info "closing stream"
    response.stream.close
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line %><br>
    <%= f.text_field :line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<h1>Editing Command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Commands</h1>

<table>
  <thead>
    <tr>
      <th>Line</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commands.each do |command| %>
      <tr>
        <td><%= command.line %></td>
        <td><%= link_to 'Show', command %></td>
        <td><%= link_to 'Edit', edit_command_path(command) %></td>
        <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1>New Command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<ul id="items">
</ul>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Activelive</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/systems/run.html.erb
<h1>Systems#run</h1>
<p>Find me in app/views/systems/run.html.erb</p>